Fix 'a' error message

diff --git a/bin/a b/bin/a
--- a/bin/a
+++ b/bin/a
@@ -29,5 +29,5 @@ if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -
 
 fi
 
-echo "Cannot find gulpfile.js, awe.yaml or package.json" >&2
+echo "Cannot find scripts/webpack.js, gulpfile.js, awe.yaml or package.json" >&2
 exit 1
