Remove Alberon stuff

diff --git a/bin/a b/bin/a
--- a/bin/a
+++ b/bin/a
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# 'a' = Asset builder (webpack, Gulp, Awe or npm as appropriate)
+# 'a' = Asset builder (webpack, Gulp or npm as appropriate)
 
-if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f awe.yaml -o -f package.json)"; then
+if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f package.json)"; then
 
     # webpack
     if [ -f scripts/webpack.js ]; then
@@ -12,11 +12,6 @@ if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -
     # Gulp
     if [ -e gulpfile.js -o -e gulpfile.coffee ]; then
         exec gulp "$@"
-    fi
-
-    # Awe (http://awe.alberon.co.uk/ - Deprecated)
-    if [ -f awe.yaml ]; then
-        exec awe "$@"
     fi
 
     # npm
@@ -29,5 +24,5 @@ if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -
 
 fi
 
-echo "Cannot find scripts/webpack.js, gulpfile.js, awe.yaml or package.json" >&2
+echo "Cannot find scripts/webpack.js, gulpfile.js or package.json" >&2
 exit 1
