Add support for webpack.sh to 'a' script

diff --git a/.bin/a b/.bin/a
--- a/.bin/a
+++ b/.bin/a
@@ -2,9 +2,13 @@
 
 # 'a' = Asset builder (webpack, Gulp or npm as appropriate)
 
-if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f package.json)"; then
+if dir="$(findup -f scripts/webpack.sh -o -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -o -f package.json)"; then
 
     # webpack
+    if [ -f scripts/webpack.sh ]; then
+        exec scripts/webpack.sh "$@"
+    fi
+
     if [ -f scripts/webpack.js ]; then
         exec scripts/webpack.js "$@"
     fi
@@ -24,5 +28,5 @@ if dir="$(findup -f scripts/webpack.js -o -e gulpfile.js -o -e gulpfile.coffee -
 
 fi
 
-echo "Cannot find scripts/webpack.js, gulpfile.js or package.json" >&2
+echo "Cannot find scripts/webpack.sh, scripts/webpack.js, gulpfile.js or package.json" >&2
 exit 1
