Upgrade to Bin CLI v0.7.1

diff --git a/.bin/bin b/.bin/bin
--- a/.bin/bin
+++ b/.bin/bin
@@ -12,7 +12,7 @@ shopt -s nullglob
 #===============================================================================
 
 # Version (set by build script - don't change in source file)
-VERSION='0.7.0'
+VERSION='0.7.1'
 
 # Executable
 BIN_EXECUTABLE="$0"
@@ -621,7 +621,11 @@ register_commands_in_directory() {
                 non_executable_files+=("$file")
             fi
         else
-            register_executable_command "$prefix$name" "$realfile"
+            # Ignore known plain text files if scripts are in the root directory,
+            # mostly in case they're on a filesystem where all files are executable
+            if ! ($is_root_dir && [[ $name =~ \.(json|md|txt|yaml|yml)$ ]]); then
+                register_executable_command "$prefix$name" "$realfile"
+            fi
         fi
     done
 }
@@ -919,6 +923,11 @@ commands_listed_in_config=()
 
 error_if_not_found=true
 keep_looking=true
+main_binconfig=''
+main_bin_dir=''
+main_bin_dir_from_root=''
+main_is_root_dir=false
+main_root=''
 merging=false
 start_directory=$PWD
 
@@ -978,7 +987,11 @@ while $keep_looking; do
         if root=$(cd "$start_directory" && findup -f .binconfig); then
             binconfig="${root%/}/.binconfig"
             bin_dir_from_root=$(bin_dir_for "$binconfig" true)
-            bin_dir="${root%/}/$bin_dir_from_root"
+            if [[ $bin_dir_from_root = '.' ]]; then
+                bin_dir=${root%/}
+            else
+                bin_dir="${root%/}/$bin_dir_from_root"
+            fi
         else
             if ! root=$(cd "$start_directory" && findup -d bin); then
                 if ! $error_if_not_found; then
@@ -1134,6 +1147,18 @@ while $keep_looking; do
     done
 
     #---------------------------------------
+    # Remember the lowest level for --create
+    #---------------------------------------
+
+    if [[ -z $main_root ]]; then
+        main_binconfig=$binconfig
+        main_bin_dir=$bin_dir
+        main_bin_dir_from_root=$bin_dir_from_root
+        main_is_root_dir=$is_root_dir
+        main_root=$root
+    fi
+
+    #---------------------------------------
     # Merge with parent?
     #---------------------------------------
 
@@ -1175,7 +1200,7 @@ list_title='Available commands'
 list_commands=(${registered_commands+"${registered_commands[@]}"})
 
 # Loop through each argument until we find a matching command
-current_directory=$bin_dir
+current_directory=$main_bin_dir
 full_command=''
 
 while [[ $# -gt $last_parameter ]]; do
@@ -1185,31 +1210,31 @@ while [[ $# -gt $last_parameter ]]; do
     # Special case for creating/editing the .binconfig file
     if [[ -z $full_command && $subcommand = '.binconfig' ]]; then
         if [[ $action = 'create' ]]; then
-            if [[ -e "$root/.binconfig" ]]; then
-                fail "$root/.binconfig already exists (use --edit to edit it)"
+            if [[ -e "$main_root/.binconfig" ]]; then
+                fail "$main_root/.binconfig already exists (use --edit to edit it)"
             fi
 
             ( # kcov-ignore-line: Usage not detected
-                if [[ $bin_dir_from_root != 'bin' ]]; then
-                    echo "dir=$bin_dir_from_root"
+                if [[ $main_bin_dir_from_root != 'bin' ]]; then
+                    echo "dir=$main_bin_dir_from_root"
                 else
                     echo
                 fi
-            ) > "$root/.binconfig" # kcov-ignore-line: Usage not detected
+            ) > "$main_root/.binconfig" # kcov-ignore-line: Usage not detected
 
-            echo "Created file $root/.binconfig"
-            open_in_editor "$root/.binconfig"
+            echo "Created file $main_root/.binconfig"
+            open_in_editor "$main_root/.binconfig"
         elif [[ $action = 'edit' ]]; then
-            if [[ ! -e "$root/.binconfig" ]]; then
+            if [[ ! -e "$main_root/.binconfig" ]]; then
                 fail 'No .binconfig file found (use --create to create one)'
             fi
 
-            bin_dir_for_binconfig=$(bin_dir_for "$root/.binconfig")
-            if [[ "$bin_dir_for_binconfig" != "$bin_dir_from_root" ]]; then
-                fail ".binconfig belongs to $bin_dir_for_binconfig/ not $bin_dir_from_root/"
+            bin_dir_for_binconfig=$(bin_dir_for "$main_root/.binconfig")
+            if [[ "$bin_dir_for_binconfig" != "$main_bin_dir_from_root" ]]; then
+                fail ".binconfig belongs to $bin_dir_for_binconfig/ not $main_bin_dir_from_root/"
             fi
 
-            open_in_editor "$root/.binconfig"
+            open_in_editor "$main_root/.binconfig"
         fi
     fi
 
@@ -1242,11 +1267,10 @@ while [[ $# -gt $last_parameter ]]; do
 
         if [[ $# -gt 0 ]]; then
             current_directory="$current_directory/$subcommand"
-            mkdir "$current_directory"
-            echo "Created subdirectory $current_directory/"
             continue
         fi
 
+        mkdir -p "$current_directory"
         script="$current_directory/$subcommand"
         echo -e "#!/usr/bin/env bash\nset -eno pipefail\n\n" >"$script"
         chmod +x "$script"
@@ -1282,8 +1306,8 @@ while [[ $# -gt $last_parameter ]]; do
 
     # If there were no prefix matches, stop searching
     if [[ ${#matching_commands[@]} -eq 0 ]]; then
-        if $is_root_dir && [[ -d "$current_directory/$subcommand" ]]; then
-            fail "Subcommands are not supported with the config option 'dir=$bin_dir_from_root'"
+        if $main_is_root_dir && [[ -d "$current_directory/$subcommand" ]]; then
+            fail "Subcommands are not supported with the config option 'dir=$main_bin_dir_from_root'"
         fi
         if [[ $subcommand = .* && -e "$current_directory/$subcommand" ]]; then
             fail "Command names may not start with '.'"
@@ -1296,7 +1320,7 @@ while [[ $# -gt $last_parameter ]]; do
         if in_array "${full_command:1}" completion create edit help version; then
             append="${NEW_LINE}${GREY}Perhaps you meant to run 'bin --${full_command:1}'?${RESET}"
         fi
-        fail "Command '${full_command:1}' not found in $bin_dir/ or $binconfig$append" $ERR_NOT_FOUND
+        fail "Command '${full_command:1}' not found in $main_bin_dir/ or $main_binconfig$append" $ERR_NOT_FOUND
     fi
 
     # Otherwise display the list of matches
@@ -1314,10 +1338,6 @@ shortened_commands=()
 
 for command in ${list_commands+"${list_commands[@]}"}; do
     executable=$(map_get command_to_executable "$command")
-    if $is_root_dir && [[ $executable =~ \.(json|md|txt|yaml|yml)$ ]]; then
-        continue
-    fi
-
     short=$(remove_extension "$command")
 
     if [[ "$short" = "$command" ]]; then
@@ -1506,7 +1526,7 @@ done
 
 if [[ ${#missing_commands[@]} -gt 0 ]]; then
     echo
-    echo "${YELLOW}Warning: The following commands listed in $binconfig do not exist:${RESET}"
+    echo "${YELLOW}Warning: The following commands listed in .binconfig do not exist:${RESET}"
     for command in ${missing_commands+"${missing_commands[@]}"}; do
         echo "[$command]"
     done
