Tweaks to Multipass config
New SSH key
Always use a named instance, not 'primary'
Use username 'dave' instead of 'ubuntu'
Ask for disk/CPUs/etc. interactively
Use *.mshome.net instead of getting the IP from Multipass manually

diff --git a/.bin/mp b/.bin/mp
--- a/.bin/mp
+++ b/.bin/mp
@@ -7,23 +7,22 @@ list-instances() {
     echo "$instances" | tail -n+2
 }
 
-primary-name() {
-    multipass get client.primary-name | tr -d '\r'
-}
-
-read-name() {
-    name=${1:-}
-
-    if [[ -z $name ]]; then
-        name=$(primary-name)
-
-        if [[ -z $name ]]; then
-            echo 'Cannot get the primary instance name' >&2
-            exit 1
-        fi
+get-name() {
+    if [[ $# -lt 1 ]]; then
+        echo 'The name parameter is required' >&2
+        exit 1
     fi
 
-    [[ $# -gt 0 ]]
+    name=$1
+}
+
+input() {
+    local variable=$1
+    local prompt=$2
+    local default=$3
+
+    read -p "$prompt [$default]: "
+    eval "$variable=\${REPLY:-\$default}"
 }
 
 case "${1:-}" in
@@ -54,59 +53,51 @@ case "${1:-}" in
         cmd=$1
         shift
 
-        read-name "$@" && shift
+        get-name "$@"
+        shift
 
-        ip=$(multipass list --format csv | awk -F , -v name="$name" 'NR > 1 && $1 == name { print $3 }')
-
-        if [[ -n $ip ]] && [[ $ip != '--' ]] && [[ $ip != 'UNKNOWN' ]]; then
-            # Remove the IP from the known hosts file because IPs are reused
-            ssh-keygen -f ~/.ssh/known_hosts -R "$ip" &>/dev/null
-
-            # Connect via regular WSL SSH not Windows SSH, and launch tmux
-            exec $cmd "ubuntu@$ip" "$@"
-        fi
-
-        if [[ "$ip" = 'UNKNOWN' ]]; then
-            echo >&2 "Cannot determine the IP of '$name'."
-            echo >&2
-            echo >&2 'Maybe disable and reenable the vEthernet adapter...'
-            echo >&2 '    https://github.com/canonical/multipass/issues/706'
-            echo >&2 'Or try creating a new instance and then restarting this one...'
-            echo >&2 '    https://github.com/canonical/multipass/issues/1052'
-            echo >&2
-            echo >&2 'These are the running VMs:'
-        else
-            echo >&2 "Cannot determine the IP of '$name'. These are the running VMs:"
-        fi
-
-        echo >&2
-        list-instances
+        $cmd "dave@$name.mshome.net" "$@"
         ;;
 
     l) # Launch
         shift
 
-        read-name "$@" && shift
+        get-name "$@"
+        shift
+
+        input cpus 'CPUs' 4
+        input disk 'Disk' 20G
+        input memory 'Memory' 4G
+        input image 'Image' lts
+
+        echo
 
         multipass launch \
             --cloud-init ~/.multipass/cloud-config.yaml \
-            --cpus 4 \
-            --disk 5G \
-            --mem 2G \
             --name "$name" \
-            "${1:-focal}"
+            --cpus "$cpus" \
+            --disk "$disk" \
+            --memory "$memory" \
+            "$@" \
+            "$image"
 
         echo
         list-instances
+
+        ssh-keygen -f ~/.ssh/known_hosts -R "$name.mshome.net" &>/dev/null
         ;;
 
     rm) # Delete & purge
         shift
 
-        read-name "$@" && shift
+        get-name "$@"
+        shift
 
-        multipass delete --purge "$name" "$@"
-        echo 'Instance deleted.'
+        multipass delete "$name" "$@"
+        echo "Instance '$name' moved to the recycle bin."
+        echo "Run 'mp purge' to permanently delete it."
+
+        ssh-keygen -f ~/.ssh/known_hosts -R "$name.mshome.net" &>/dev/null
         ;;
 
     scp) # Transfer
