Rename 'extract' to 'tarx'
Matches 'tarc' and 'wgetx'; easier to type; and it's what I always think it's called because I used to have an alias 'tarc=tar cf'

diff --git a/.bin/tarx b/.bin/tarx
--- a/.bin/tarx
+++ b/.bin/tarx
@@ -2,7 +2,7 @@
 set -o errexit -o nounset -o pipefail
 
 if [[ -z ${1:-} ]]; then
-    echo "Usage: extract <filename>"
+    echo "Usage: tarx <filename>"
 elif [[ -f $1 ]]; then
     case $1 in
         *.tar.bz2)  tar xjf "$1"    ;;
@@ -16,7 +16,7 @@ elif [[ -f $1 ]]; then
         *.tgz)      tar xzf "$1"    ;;
         *.zip)      unzip "$1"      ;;
         *.Z)        uncompress "$1" ;;
-        *)          echo "'$1' cannot be extracted by extract" >&2 ;;
+        *)          echo "'$1' cannot be extracted by tarx" >&2 ;;
     esac
 else
     echo "'$1' is not a valid file" >&2
