Update 'cfg' to match the Alberon version

diff --git a/.dotfiles/cfg b/.dotfiles/cfg
--- a/.dotfiles/cfg
+++ b/.dotfiles/cfg
@@ -16,6 +16,8 @@
     set -o errexit -o pipefail -o nounset
 
     # Settings
+    # If you want to make your own copy of this script on your own domain, set this to your GitHub username
+    user='davejamesmiller'
     branch='main'
 
     # Should be in home directory anyway, but just in case...
@@ -55,13 +57,39 @@
         fi
     fi
 
+    # Ask which repository to use
+    if [[ -z $user ]]; then
+        echo
+        say 'Please enter the GitHub username to use'
+        echo 'For a shared account please accept the default (alberon).'
+        echo 'To set up your own Dotfiles see https://github.com/alberon/dotfiles.'
+        echo
+        while [[ -z $user ]]; do
+            read -p '> [alberon] ' answer || exit 4
+
+            # Default
+            if [ -z "$answer" ]; then
+                answer="alberon"
+            fi
+
+            # Make sure it exists
+            if git ls-remote "git://github.com/$answer/dotfiles.git" >/dev/null; then
+                user="$answer"
+            else
+                echo
+                error "Cannot find repo at https://github.com/$answer/dotfiles"
+                echo "Please check and try again"
+                echo
+            fi
+        done
+        echo
+    fi
 
     # Download the repository
     say 'Downloading dotfiles repository...'
-    git init --initial-branch main 2>/dev/null || git init || fail 'Failed to initialise the Git repo'
-    git remote add origin 'https://github.com/davejamesmiller/dotfiles.git' || fail 'Failed to configure the Git remote'
-    git remote set-url --push origin 'git@github.com:davejamesmiller/dotfiles.git' || fail 'Failed to configure the Git push URL'
-    git remote add alberon https://github.com/alberon/dotfiles.git
+    git init --initial-branch "$branch" 2>/dev/null || git init || fail 'Failed to initialise the Git repo'
+    git remote add origin "https://github.com/$user/dotfiles.git" || fail 'Failed to configure the Git remote'
+    git remote set-url --push origin "git@github.com:$user/dotfiles.git" || fail 'Failed to configure the Git push URL'
     git fetch --depth=1 origin || fail 'Failed to download the Git repository'
 
     # Automatically delete known skeleton files
@@ -148,4 +176,14 @@
 
     # Run any post-install commands, e.g. prepare config file
     say 'Running post-install script...'
-) && exec ~/.dotfiles/post-install
+) || return
+
+# Current version (Oct 2021)
+if [[ -f ~/.dotfiles/post-install ]]; then
+    exec ~/.dotfiles/post-install
+fi
+
+# Legacy version
+[[ -x ~/bin/cfg-install ]] && ~/bin/cfg-install
+[[ -x ~/bin/cfg-update ]] && ~/bin/cfg-update
+exec bash -l
