Use djm.me instead of davejamesmiller.com for Git

diff --git a/.dotfiles/cfg b/.dotfiles/cfg
--- a/.dotfiles/cfg
+++ b/.dotfiles/cfg
@@ -58,19 +58,19 @@
         fail 'SSH key not found'
     fi
 
-    # Add GitHub SSH public key
-    say 'Adding DaveJamesMiller.com SSH public key'
+    # Add SSH public key
+    say 'Adding SSH public key'
     mkdir -p .ssh
     chmod 700 .ssh
-    echo 'davejamesmiller.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJmp1lkU67D50pSpn0JUDo/GJse+jOzYg0bE9Gxr+Acu' >> .ssh/known_hosts
-    echo 'davejamesmiller.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNhNN8fpgK46rNG2gdYjaYUx/oCHRf3GpS4ggwEjkjaaQxsQb0kkXnmrlqb+EV/CEvkG7oRDqqCtthEQDrhkyZo=' >> .ssh/known_hosts
-    echo 'davejamesmiller.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClC2+HP3+3pGEZbeI4EPxEPCfKqy6S2SDfhHP+hzv0dW7dO3B5kC0xoUl9BdGcRQ+G99NhNUvuAjuOCU88VuTajfKJQq95Sk1laGsrc6HUrLUnEow1rK+jo5mwArARPkvD0cU4Gmpvn6XOKTJQcvz5uNA/KA6ZXMracqo4kFHRAde+/2L5DizjwE2Eik9k9oOcamU6lE4kcJdJFj7HVRs553QClAzYJfmJSNMsr8Noyl4Vw5Mhn2Ho+3njgM1BvFyphC5NSHW7mOL3OCBANNlYZWer7tR6lHjQwjAuZezN7vl0WiVleFiX4Wju8hRxC/7CX1Kvr9jYjzSxOGytpVGz0+OA5T8nHueOS/MibT/87miGdOIE8m8lv9ll5tK9QotehP5JZrzI+9+BX0L0/zTpi/Jt3eRhbhUV7HZbhwZwIUT0AxqOln6aTvZy+UNYk5D1MdcIEQ4lfM1YUgEU3lUmQ7W9Gwb651of9KnqtjpHw1SyfPoQalGyM4KofifyE2s=' >> .ssh/known_hosts
+    echo 'djm.me ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJmp1lkU67D50pSpn0JUDo/GJse+jOzYg0bE9Gxr+Acu' >> .ssh/known_hosts
+    echo 'djm.me ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNhNN8fpgK46rNG2gdYjaYUx/oCHRf3GpS4ggwEjkjaaQxsQb0kkXnmrlqb+EV/CEvkG7oRDqqCtthEQDrhkyZo=' >> .ssh/known_hosts
+    echo 'djm.me ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClC2+HP3+3pGEZbeI4EPxEPCfKqy6S2SDfhHP+hzv0dW7dO3B5kC0xoUl9BdGcRQ+G99NhNUvuAjuOCU88VuTajfKJQq95Sk1laGsrc6HUrLUnEow1rK+jo5mwArARPkvD0cU4Gmpvn6XOKTJQcvz5uNA/KA6ZXMracqo4kFHRAde+/2L5DizjwE2Eik9k9oOcamU6lE4kcJdJFj7HVRs553QClAzYJfmJSNMsr8Noyl4Vw5Mhn2Ho+3njgM1BvFyphC5NSHW7mOL3OCBANNlYZWer7tR6lHjQwjAuZezN7vl0WiVleFiX4Wju8hRxC/7CX1Kvr9jYjzSxOGytpVGz0+OA5T8nHueOS/MibT/87miGdOIE8m8lv9ll5tK9QotehP5JZrzI+9+BX0L0/zTpi/Jt3eRhbhUV7HZbhwZwIUT0AxqOln6aTvZy+UNYk5D1MdcIEQ4lfM1YUgEU3lUmQ7W9Gwb651of9KnqtjpHw1SyfPoQalGyM4KofifyE2s=' >> .ssh/known_hosts
     chmod 600 .ssh/known_hosts
 
     # Download the repository
     say 'Downloading dotfiles repository'
     git init || fail 'Failed to initialise the Git repo'
-    git remote add origin 'git@davejamesmiller.com:dave/dotfiles.git' || fail 'Failed to configure the Git remote'
+    git remote add origin 'git@djm.me:dave/dotfiles.git' || fail 'Failed to configure the Git remote'
     git fetch --depth=1 origin || fail 'Failed to download the Git repository'
 
     # Check out the files
